### ISSUE TITLE
Maybe rename Blob to something else?

### ISSUE THREAD

**Issue by switz** [cawfree/react-native-blobular#1]
This is a really cool library, but I recommend renaming `Blob` to something else since `Blob` already means something in javascript. Granted it's a Web/Browser API, but it still could lead to some clashing or confusion down the line.

Thanks for the cool code!

https://developer.mozilla.org/en-US/docs/Web/API/Blob

**Comment by cawfree** [comment]
That really didn't occur to me, I think you're totally right. I'll rename the export to something a little different.

As a workaround for now, you can use `import { Blob as Goo} from react-native-blobular`.

Thanks!
